### ISSUE TITLE
Creditcard payments error on PHP 8.1+

### ISSUE THREAD

**Issue by roesware** [buckaroo-it/WooCommerce#281]
Unable to pay with creditcard transactions! 

When selecting creditcard payment method in the WooCommerce checkout:

`PHP Deprecated: Creation of dynamic property BuckarooCreditCard::$channel is deprecated in /wp-content/plugins/wc-buckaroo-bpe-gateway/gateway-buckaroo.php`

Using PHP 8.3.10 & PHP 8.2 on WordPress 6.6.2 with the newest Buckaroo WP version.

I know it's not a fatal error, but the payments currently can't be completed due to this error.
Already had customer backing out of completing the transaction..

**Comment by Buckaroo-Rene** [comment]
Hi @roesware,

First of all thank you for reaching out to us regarding this issue.
I've tried to reproduce the issue on one of our own stagings with the versions as showed below. Unfortunately I was not able to reproduce the issue.
- WordPress 6.6.2
- WooCommerce 9.3.1
- PHP 8.2.20

Since it is referring to a channel error this could also be related to specific settings from the plugin or the Buckaroo Plaza.
Can you perhaps send this issue to support@buckaroo.nl so my colleague's from our technical support department can take a closer look at it.

Please also provide your **website key** or a **transaction key** from one of the transaction request examples so they can specifically look into your account for the error.
Perhaps you are using the inline version instead of the redirect version for creditcards in the plugin?
To use Creditcards inline you'll need additional permissions.

![Settings](https://github.com/user-attachments/assets/0e9ef694-8926-4ef7-85b1-eb324265b64c)

Please send us an e-mail with the additional information and we'll pick it up from there.

Best Regards,
René

**Comment by Buckaroo-Rene** [comment]
Hi @roesware ,

I did not see any message under your name coming in at our support department.
Perhaps you used a different name and the issue is already resolved.
If not, please let us know the ticket/case number from support that you got back from us when sending the e-mail to support@buckaroo.nl

For now I will close this ticket, please let us know if the issue is still active so I can reopen it.

Best regards,
René

**Comment by roesware** [comment]
The issue is still there; I've just sent an email as advised

**Comment by Buckaroo-Rene** [comment]
Hi @roesware ,

Thanks, we received the information and already looked into it.
Our technical support team will send you a reply as soon as possible.
